services:
  minio:
    container_name: review-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: review
      MINIO_ROOT_PASSWORD: pass1234
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
