# .env file 처리 해야함
services:
  minio:
    container_name: review-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/review/minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: review-db
    ports:
      - "1521:1521"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/review/oracle-data:/opt/oracle/oradata
    restart: always

  be:
    container_name: review-be
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - minio
      - oracle-db
    restart: always

  fe:
    container_name: review-fe
    build:
      context: ../View
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - be
    restart: always