name: Deploy Review Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use runner on EC2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Create .env from secrets  # Make ".env" from Git Secrets
        run: |
          cd infra
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Create frontend env
        run: |
          cd View
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" > .env.production

      - name: Stop & remove previous containers # Docker compose down
        run: |
          cd infra
          docker compose down || true

      - name: Build new containers              # Build Container
        run: |
          cd infra
          docker compose build --no-cache

      - name: Start containers                   # Docker Compose Up
        run: |
          cd infra
          docker compose up -d
